# Generated by Django 3.2.25 on 2024-06-08 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'following')},
        ),
    ]
